### ISSUE TITLE
Meaning of parameter nnCacheSizePowerOfTwo

### ISSUE THREAD

**Issue by Victor-Ch** [sun-yuliang/PentaZen-2019#3]
There is configuration parameter 'nnCacheSizePowerOfTwo' in the configuration file 'config-pentazen.cfg'.
What does mean its value (default is 15)? Can it be converted in Mb?

**Comment by sun-yuliang** [comment]
Quote from the comments in KataGo default config file:

# nnCacheSizePowerOfTwo:
# This controls the NN Cache size, which is the primary RAM/memory use.
# Increase this if you don't mind the memory use and want better performance for searches with
# tens of thousands of visits or more. Decrease this if you want to limit memory usage.
#
# If you're someone who is happy to do a bit of math - each neural net entry takes very
# approximately 1.5KB, except when using whole-board ownership/territory visualizations, each
# entry will take very approximately 3KB. The number of entries is (2 ** nnCacheSizePowerOfTwo),
# for example 2 ** 18 = 262144.

In PentaZenNN, this value serves the same purpose.

**Comment by sun-yuliang** [comment]
Quote from the comments in KataGo config file:

nnCacheSizePowerOfTwo:
This controls the NN Cache size, which is the primary RAM/memory use.
Increase this if you don't mind the memory use and want better performance for searches with
tens of thousands of visits or more. Decrease this if you want to limit memory usage.

If you're someone who is happy to do a bit of math - each neural net entry takes very
approximately 1.5KB, except when using whole-board ownership/territory visualizations, each
entry will take very approximately 3KB. The number of entries is (2 ** nnCacheSizePowerOfTwo),
for example 2 ** 18 = 262144.

In PentaZenNN, this value serves the same purpose.
